language: python
python:
- 2.7
install:
- pip install sphinx sphinx-autobuild sphinx_rtd_theme
- pip install recommonmark
- pip install sphinxcontrib-googleanalytics
- pip install awscli
script:
- make html
before_deploy:
- aws s3 rm s3://docs.mattermost.com.rocksolitinc.com/ --recursive --region us-east-2
deploy:
- provider: s3
  access_key_id: AKIAJWSK4VIQE3VQ3LVQ
  secret_access_key:
    secure: c8UaZhLjddjycmiGi/Qzkmu5yN8Gu5OBuFmavUeXClRbwOFEH1Rq/mFqAdmLYgaDXbozAe+CKldP0XQMvvRvhurmxiaDCFPROhDmkvQ/RXQ5MQbs8tuNFRf+BuXI+uXJPNRFSSmWOEMHhBbkwgQEHfMCgKRtgUsc/gSvcVz8/St0iacpABMWzKFZy5GBSqFM7XQUsklyHVO2Is+KkMywd1nE3wmZiqq3chXE42DzI0Rw/WbkDfAsuzSiG6lDEdSH0lFDnUnDFW4lqBrGYXRrvR2zzz0KTayzafXhmiDv2D6aDfaRkWZvR0+N1S5YyAzZHIRiYjhNNNBS1zkhS93Z8p4BSA0jtg3f4z66fsiY1o6snTtmNrkP7i4TZPWPyW62gYSrrkDVUVnvcOcFeJ13fC8wiZy/kr6iZi0NiWcFZs1iOQOIrbL905I8Mwd9Jizu3nFTVp/vh/WNzDwnuF2q44fMdTjicRCHDJHpN48OKFHu7+SujfooPgLIefNUgHwvzeDJPvz55Dioc9eKvLb/CqKCta8SwrUQbCqSfVY3VKMmng5Qc2aSfFHrhOjxFrGnyfbWDId9SbqMCUnFaQrVZzlqON7PGL23Pqy4WcNoLERaobwsFq2nVzsy2vK/qtWmDNp+x+upqhdq6PUop08zciAbyaYi54lQQs1EOoxJ0Mw=
  bucket: docs.mattermost.com.rocksolitinc.com
  local_dir: build/html
  acl: public_read
  region: us-east-2
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: shieldsjared/docs-ci-sandbox
    branch: master
    python: 2.7
