language: python
python:
- 2.7
install:
- pip install sphinx sphinx-autobuild sphinx_rtd_theme
- pip install recommonmark
- pip install sphinxcontrib-googleanalytics
- pip install awscli
script:
- make html
before_deploy:
- aws s3 rm s3://docs.mattermost.com.rocksolitinc.com/ --recursive --region us-east-2
deploy:
- provider: s3
  access_key_id: AKIAJWSK4VIQE3VQ3LVQ
  secret_access_key:
    secure: "N6BeIUhmLKWnDEGhRwolzfawQ8Aq/zQcO1atfdTvMRFg+YC7R1gHrz0UvpxSpRwXZGAAN2GzASUTDXrkuzewtqcNsJhqIgmkLZIhJBjCzPbxWjqylX2N+e2Vc7mqjgQtSIfyDtv8HqGTQ3zGzBEfYuhNYr2iX/TZfRi/Z9hwBNo9OKvR0CmfQSlDwJozMqpCwZ0xZbBSiJRrxpFVHs7phopiWulOFLXDBNdg3rNSsWBuuYzdq1nG1iBvIERyvdmqjoucd0OR8EWPUpcxH1HTTbJwRb27nlLzEJ/NMv5wRVLCAWQM7UEcgCBVVmo9an2FRJ9erdDtEUl2hOA7VGt6yLzv3ftRgN5l0dI/2tUwxBHJMDxY9VlJnf9VFxCMLWziDPzzwU+QlkEqEp1XlIevCJHBNmjUkwMn33MDYSKLOzn/REWqlTAjBoAWVnkx9VrIZHQHaVjLJJ/dQSJbtRma6uhcrm0BQRGbUDzx42wAX5UepJafvK4FM4H58+XsolRDlD6lOdCtNqMggihKuRw/f978iIAZj7oM+gYVVEhxBHo0rzujCyu41CYpyWePm/0LhqT3vKnVYjoZNiuze3qTSn8V4xE6GTjv1pGeYKEValqb37LJAvGDkzkPvPxTdCIFFn8hUqJjlyI/3PKJLHQqles/TfbneK6oNFhunInnj6Y="
  bucket: docs.mattermost.com.rocksolitinc.com
  local_dir: build/html
  acl: public_read
  region: us-east-2
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: shieldsjared/docs-ci-sandbox
    branch: master
    python: 2.7
