language: python
python:
- 2.7
install:
- pip install sphinx sphinx-autobuild sphinx_rtd_theme
- pip install recommonmark
- pip install sphinxcontrib-googleanalytics
- pip install awscli
script:
- make html
before_deploy:
- aws s3 rm s3://docs.mattermost.com.rocksolitinc.com/ --recursive --region us-east-2
deploy:
- provider: s3
  access_key_id: AKIAJWSK4VIQE3VQ3LVQ
  secret_access_key:
    secure: YnvFkBnBbrkrEe++4oCnR35f/fVYBWvN+Od/OQgr6DnCbBvbehr5XeR/nA1v1TrqhnwQSeh4WQ0f8mV9p2XWJ3VxgOeLAWZx3vlU4vlcDePDAPDfdTqCtQkmR34bLExEarhpvVeEhQAB8i8IdAVbmkRtLNj8WL5eOiXhRqpCWhFe2HvlETWSyy0B8zmBJieJ4dyswiUhRWg1sMqJMgUmverC2tFkVp2Try7q/wXQ0pHGf7CnpKbqk1B4RUYZBtCtgjLjYYYHjSshAoa08YVPoxOz6ZOJ8ksbSYIDHi7ynOky0AU2PKjwNdAV/gUFp1MltEfKK7QbVDBbbsfrY/7ELyL0HZd33DhFAQzisIWglqj1KU/d++3GNA8dJH0fEy3IVi9dkD3hwv9XWu0gFKayxSmn0wKk8ySVgV2cX/Zfxt25dzcspkTsUTzgeQpG+9dbuhkbdY4bEXbX/YB8AVoDAA1pGGCmtVcGcXkGUODvlvTseXWZ9ukc8z4YnyUghfsSg9rn5SO2DbdIirjyl0/8M4UtMDZnEMD6i1S7KRIEVcaqawV+lFjZ8KeJn7jLFKUK/hO1+MoLTJelWDFgK/c9DiLh6AN8vxyvwrHnx6vmX7qGT0DeCRaJodrD8kEWwyqqKWyx/stk7b1XCOTUPhGCfrs5P8eKkMh9nPSD63J1ja8=
  bucket: docs.mattermost.com.rocksolitinc.com
  local_dir: build/html
  acl: public_read
  region: us-east-2
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: shieldsjared/docs-ci-sandbox
    branch: master
    python: 2.7
